# Generated by Django 5.0 on 2024-10-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivelDeAcesso', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('creci', models.CharField(max_length=100, unique=True)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
    ]
